server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/eugene/Workspace/Eugene/spring-cloud-samples/config-server/src/main/resources/config/licensingservice